title: QuSZIT
email: nemkin@cs.bme.hu
description: Kvantuminformatikai kutatócsoport a BME VIK karának SZIT tanszékén.
lang: hu-HU

domain: cs.nemk.in
url: "https://cs.nemk.in/"

github_username: nemkin

# Build settings
remote_theme: nemkin/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
