title: SZIT Quantum
email: nemkin@cs.bme.hu
description: Kvantuminformatikai kutatócsoport a SZIT-en.

# If you want to force HTTPS, specify the domain without the http at the start, e.g. example.com.
domain: szitquantum.nemkindev.com
url: "http://szitquantum.nemkindev.com"

github_username: nemkin

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme