title: SZIT Quantum
email: nemkin@cs.bme.hu
description: Kvantuminformatikai kutatócsoport a SZIT-en.

# If you want to force HTTPS, specify the domain without the http at the start, e.g. example.com.
domain: cs.bme.hu
url: "https://cs.bme.hu"
baseurl: "/quantum"

github_username: nemkin

# Build settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
